### ISSUE TITLE
cyclesOption node is empty

### ISSUE THREAD

**Issue by acorsei** [boberfly/GafferCycles#34]
creating a cycleOption node results in an empty node. see bellow screencapture and console output. thanks

![Screenshot_gaffer_20191216200855](https://user-images.githubusercontent.com/7030609/70935251-0f9a7d00-2040-11ea-8010-468d34d7df44.png)
Traceback (most recent call last):
  File "/media/Media_B/repo_lnx/gaffer-0.55.1.0-linux/python/GafferUI/Widget.py", line 937, in eventFilter
    self.__showHide( qObject, qEvent )
  File "/media/Media_B/repo_lnx/gaffer-0.55.1.0-linux/python/GafferUI/Widget.py", line 1004, in __showHide
    widget._visibilityChangedSignal( widget )
IECore.Exception: Traceback (most recent call last):
  File "/media/Media_B/repo_lnx/gaffer-0.55.1.0-linux/python/GafferUI/LazyMethod.py", line 140, in __visibilityChanged
    cls.__doPendingCalls( widget, method )
  File "/media/Media_B/repo_lnx/gaffer-0.55.1.0-linux/python/GafferUI/LazyMethod.py", line 174, in __doPendingCalls
    method( widget, *pendingCall.args, **pendingCall.kw )
  File "/media/Media_B/repo_lnx/gaffer-0.55.1.0-linux/python/GafferUI/PlugLayout.py", line 250, in __updateLazily
    self.__update()
  File "/media/Media_B/repo_lnx/gaffer-0.55.1.0-linux/python/GafferUI/PlugLayout.py", line 263, in __update
    self.__updateSummariesWalk( self.__rootSection )
  File "/media/Media_B/repo_lnx/gaffer-0.55.1.0-linux/python/GafferUI/PlugLayout.py", line 363, in __updateSummariesWalk
    self.__updateSummariesWalk( subsection )
  File "/media/Media_B/repo_lnx/gaffer-0.55.1.0-linux/python/GafferUI/PlugLayout.py", line 360, in __updateSummariesWalk
    section.summary = self.__metadataValue( self.__parent, self.__layoutName + ":section:" + section.fullName + ":summary" ) or ""
  File "/media/Media_B/repo_lnx/gaffer-0.55.1.0-linux/python/GafferUI/PlugLayout.py", line 422, in __metadataValue
    return Gaffer.Metadata.value( plugOrNode, name )
  File "/home/acorsei/applications/gafferCycles/python/GafferCyclesUI/CyclesOptionsUI.py", line 138, in __samplingSummary
    if plug["useAdaptiveSampling"]["enabled"].getValue() :
KeyError: "'useAdaptiveSampling' is not a child of 'options'"

**Comment by boberfly** [comment]
Hey @acorsei 

Is this with the experimental build I just published? It's pretty raw but cheers for the heads-up I know what it is to fix it, I'll make a new build when I get home tonight.

Cheers!

**Comment by acorsei** [comment]
Hi @boberfly 
Confirmed, it’s the experimental build. No worries, great job and will let you know if hit in others matters.
Amazing and thanks a lot,
Regards

**Comment by boberfly** [comment]
Hey @acorsei 

I've fixed this build here:
https://github.com/boberfly/GafferCycles/releases/tag/0.12.0-experimental

Cheers

**Comment by acorsei** [comment]
Thanks @boberfly 
that fix the matter.
